# Generated by Django 6.1 on 2026-08-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', '特定技能1号'), ('2', '特定技能2号')], default='1', max_length=1)),
                ('category', models.CharField(max_length=100, verbose_name='Chủ đề')),
                ('question_jp', models.TextField(verbose_name='Câu hỏi tiếng Nhật')),
                ('question_vi', models.TextField(verbose_name='Câu hỏi tiếng Việt')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, verbose_name='Giải thích')),
            ],
        ),
    ]
