# Generated by Django 6.1 on 2026-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a_vi',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Option A tiếng Việt'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_vi',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Option B tiếng Việt'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_vi',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Option C tiếng Việt'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_vi',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Option D tiếng Việt'),
        ),
    ]
