# Generated by Django 6.1 on 2026-08-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_question_option_a_vi_question_option_b_vi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', '特定技能1号'), ('2', '特定技能2号')], default='1', max_length=1)),
                ('title', models.CharField(max_length=200, verbose_name='Tên đề')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('is_free', models.BooleanField(default=True, verbose_name='Miễn phí')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('theory', '学科試験'), ('practical', '実技試験')], default='theory', max_length=20, verbose_name='Phần thi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='Giải thích'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_vi',
            field=models.TextField(blank=True, default='', verbose_name='Câu hỏi tiếng Việt'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Số thứ tự câu')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', through='study.ExamQuestion', to='study.question'),
        ),
    ]
