# Generated by Django 6.1 on 2026-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_exam_question_section_alter_question_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d_vi',
        ),
        migrations.AddField(
            model_name='exam',
            name='time_limit',
            field=models.PositiveIntegerField(default=70, verbose_name='Thời gian thi (phút)'),
        ),
        migrations.AddField(
            model_name='question',
            name='practical_type',
            field=models.CharField(blank=True, choices=[('', '---'), ('judgment', '判断試験'), ('planning', '計画立案')], default='', max_length=20, verbose_name='Loại câu thực hành'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exam',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('hygiene', '衛生管理'), ('cooking', '飲食物調理'), ('service', '接客全般')], default='hygiene', max_length=20, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='Đáp án đúng'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=500, verbose_name='Đáp án A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a_vi',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Đáp án A tiếng Việt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=500, verbose_name='Đáp án B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b_vi',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Đáp án B tiếng Việt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=500, verbose_name='Đáp án C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c_vi',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Đáp án C tiếng Việt'),
        ),
    ]
