# Generated by Django 6.1 on 2026-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_remove_question_option_d_remove_question_option_d_vi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Điểm'),
        ),
    ]
