# Generated by Django 6.1 on 2026-08-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_ruby',
            field=models.TextField(blank=True, default='', verbose_name='Câu hỏi tiếng Nhật + Furigana'),
        ),
    ]
