# Generated by Django 6.1 on 2026-08-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_question_question_ruby'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a_ruby',
            field=models.TextField(blank=True, default='', verbose_name='Đáp án A Furigana'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_ruby',
            field=models.TextField(blank=True, default='', verbose_name='Đáp án B Furigana'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_ruby',
            field=models.TextField(blank=True, default='', verbose_name='Đáp án C Furigana'),
        ),
    ]
