# Generated by Django 6.1 on 2026-08-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_question_option_a_ruby_question_option_b_ruby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_vi',
            field=models.TextField(blank=True, default='', verbose_name='Giải thích tiếng Việt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='Giải thích tiếng Nhật'),
        ),
    ]
