# Generated by Django 6.1 on 2026-08-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_question_explanation_vi_alter_question_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_jp', models.CharField(max_length=120)),
                ('title_vi', models.CharField(max_length=120)),
                ('description_vi', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='📘', max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Nhóm tài liệu',
                'verbose_name_plural': 'Nhóm tài liệu',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title_jp', models.CharField(max_length=200)),
                ('title_furigana', models.CharField(blank=True, default='', max_length=250)),
                ('title_vi', models.CharField(max_length=200)),
                ('content_jp', models.TextField()),
                ('content_furigana', models.TextField(blank=True, default='')),
                ('content_vi', models.TextField()),
                ('exam_notes_vi', models.TextField(blank=True, default='')),
                ('source_title', models.CharField(blank=True, default='', max_length=250)),
                ('source_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='study.learningcategory')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Bài học',
                'ordering': ['category__order', 'order', 'id'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='QuickQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_jp', models.TextField()),
                ('question_furigana', models.TextField(blank=True, default='')),
                ('question_vi', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('explanation_vi', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_questions', to='study.lesson')),
            ],
            options={
                'verbose_name': 'Câu luyện nhanh',
                'verbose_name_plural': 'Câu luyện nhanh',
                'ordering': ['order', 'id'],
            },
        ),
    ]
