# Generated by Django 6.1 on 2026-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_seed_library_starter_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hygiene', '衛生管理 - Quản lý vệ sinh'), ('cooking', '飲食物調理 - Chế biến'), ('service', '接客全般 - Phục vụ khách hàng')], max_length=20)),
                ('word_jp', models.CharField(max_length=120, verbose_name='Từ tiếng Nhật')),
                ('furigana', models.CharField(max_length=150, verbose_name='Furigana')),
                ('meaning_vi', models.CharField(max_length=250, verbose_name='Nghĩa tiếng Việt')),
                ('example_jp', models.TextField(blank=True, default='', verbose_name='Ví dụ tiếng Nhật')),
                ('example_furigana', models.TextField(blank=True, default='', verbose_name='Furigana của ví dụ')),
                ('example_vi', models.TextField(blank=True, default='', verbose_name='Nghĩa của ví dụ')),
                ('exam_note_vi', models.TextField(blank=True, default='', verbose_name='Ghi chú khi thi')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Từ vựng',
                'verbose_name_plural': 'Kho từ vựng',
                'ordering': ['category', 'order', 'id'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='study_vocab_categor_dfa7bc_idx')],
            },
        ),
    ]
