# Generated by Django 6.1 on 2026-08-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_seed_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyentry',
            name='source_title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Tên nguồn'),
        ),
        migrations.AddField(
            model_name='vocabularyentry',
            name='source_url',
            field=models.URLField(blank=True, default='', verbose_name='Đường dẫn nguồn'),
        ),
    ]
