from django.db import migrations


SOURCES = {
    'hygiene': 'https://www.jfnet.or.jp/wp/wp-content/uploads/2025/09/jf_hygiene_controls_text_ja_v1.2.pdf',
    'cooking': 'https://www.jfnet.or.jp/wp/wp-content/uploads/2025/09/jf_preparation_of_food_and_drink_text_ja_v1.1.pdf',
    'service': 'https://www.jfnet.or.jp/wp/wp-content/uploads/2025/09/230808jf_customer_service_text_ja_v1.1.pdf',
}

VOCABULARY = {
    'hygiene': [
        ('衛生管理', 'えいせいかんり', 'quản lý vệ sinh'),
        ('食中毒', 'しょくちゅうどく', 'ngộ độc thực phẩm'),
        ('予防', 'よぼう', 'phòng ngừa'),
        ('三原則', 'さんげんそく', 'ba nguyên tắc'),
        ('細菌', 'さいきん', 'vi khuẩn'),
        ('ウイルス', 'ういるす', 'vi-rút'),
        ('腸管出血性大腸菌', 'ちょうかんしゅっけつせいだいちょうきん', 'vi khuẩn E. coli gây xuất huyết đường ruột'),
        ('カンピロバクター', 'かんぴろばくたー', 'vi khuẩn Campylobacter'),
        ('サルモネラ属菌', 'さるもねらぞくきん', 'vi khuẩn Salmonella'),
        ('黄色ブドウ球菌', 'おうしょくぶどうきゅうきん', 'tụ cầu vàng'),
        ('ウェルシュ菌', 'うぇるしゅきん', 'vi khuẩn Clostridium perfringens'),
        ('セレウス菌', 'せれうすきん', 'vi khuẩn Bacillus cereus'),
        ('腸炎ビブリオ', 'ちょうえんびぶりお', 'vi khuẩn Vibrio gây viêm ruột'),
        ('ノロウイルス', 'のろういるす', 'vi-rút Noro'),
        ('寄生虫', 'きせいちゅう', 'ký sinh trùng'),
        ('アニサキス', 'あにさきす', 'ký sinh trùng Anisakis'),
        ('原材料', 'げんざいりょう', 'nguyên liệu'),
        ('受入れ', 'うけいれ', 'tiếp nhận hàng'),
        ('納品', 'のうひん', 'giao hàng'),
        ('冷蔵庫', 'れいぞうこ', 'tủ lạnh'),
        ('冷凍庫', 'れいとうこ', 'tủ đông'),
        ('温度管理', 'おんどかんり', 'quản lý nhiệt độ'),
        ('交差汚染', 'こうさおせん', 'nhiễm chéo'),
        ('二次汚染', 'にじおせん', 'nhiễm bẩn thứ cấp'),
        ('洗浄', 'せんじょう', 'rửa làm sạch'),
        ('消毒', 'しょうどく', 'khử trùng'),
        ('殺菌', 'さっきん', 'diệt khuẩn'),
        ('調理器具', 'ちょうりきぐ', 'dụng cụ nấu ăn'),
        ('まな板', 'まないた', 'thớt'),
        ('包丁', 'ほうちょう', 'dao bếp'),
        ('従業員', 'じゅうぎょういん', 'nhân viên'),
        ('健康管理', 'けんこうかんり', 'quản lý sức khỏe'),
        ('作業着', 'さぎょうぎ', 'quần áo làm việc'),
        ('着用', 'ちゃくよう', 'mặc; đeo'),
        ('手洗い', 'てあらい', 'rửa tay'),
        ('清掃', 'せいそう', 'vệ sinh, quét dọn'),
        ('廃棄物', 'はいきぶつ', 'chất thải'),
        ('処理', 'しょり', 'xử lý'),
        ('重要管理ポイント', 'じゅうようかんりぽいんと', 'điểm quản lý quan trọng'),
        ('記録', 'きろく', 'ghi chép; hồ sơ'),
        ('加熱不足', 'かねつぶそく', 'gia nhiệt không đủ'),
        ('体調不良', 'たいちょうふりょう', 'tình trạng sức khỏe không tốt'),
        ('おう吐', 'おうと', 'nôn ói'),
        ('下痢', 'げり', 'tiêu chảy'),
        ('腹痛', 'ふくつう', 'đau bụng'),
        ('異物', 'いぶつ', 'dị vật'),
        ('混入', 'こんにゅう', 'lẫn vào; nhiễm lẫn'),
        ('保存', 'ほぞん', 'bảo quản'),
        ('賞味期限', 'しょうみきげん', 'hạn dùng ngon nhất'),
        ('消費期限', 'しょうひきげん', 'hạn sử dụng an toàn'),
        ('中心温度', 'ちゅうしんおんど', 'nhiệt độ trung tâm'),
        ('生肉', 'なまにく', 'thịt sống'),
        ('二枚貝', 'にまいがい', 'động vật hai mảnh vỏ'),
        ('加熱', 'かねつ', 'gia nhiệt'),
        ('冷却', 'れいきゃく', 'làm nguội'),
    ],
    'cooking': [
        ('飲食物調理', 'いんしょくぶつちょうり', 'chế biến đồ ăn và thức uống'),
        ('食材', 'しょくざい', 'nguyên liệu thực phẩm'),
        ('下処理', 'したしょり', 'sơ chế'),
        ('計量', 'けいりょう', 'cân đo'),
        ('解凍', 'かいとう', 'rã đông'),
        ('切る', 'きる', 'cắt'),
        ('刻む', 'きざむ', 'băm; thái nhỏ'),
        ('むく', 'むく', 'gọt; bóc vỏ'),
        ('洗う', 'あらう', 'rửa'),
        ('混ぜる', 'まぜる', 'trộn'),
        ('こねる', 'こねる', 'nhào'),
        ('焼く', 'やく', 'nướng; áp chảo'),
        ('煮る', 'にる', 'ninh; nấu'),
        ('蒸す', 'むす', 'hấp'),
        ('揚げる', 'あげる', 'chiên ngập dầu'),
        ('炒める', 'いためる', 'xào'),
        ('茹でる', 'ゆでる', 'luộc'),
        ('炊く', 'たく', 'nấu cơm'),
        ('盛り付け', 'もりつけ', 'trình bày món ăn'),
        ('調味料', 'ちょうみりょう', 'gia vị'),
        ('塩', 'しお', 'muối'),
        ('砂糖', 'さとう', 'đường'),
        ('酢', 'す', 'giấm'),
        ('醤油', 'しょうゆ', 'nước tương'),
        ('味噌', 'みそ', 'tương miso'),
        ('出汁', 'だし', 'nước dùng dashi'),
        ('香辛料', 'こうしんりょう', 'gia vị thơm; hương liệu'),
        ('火加減', 'ひかげん', 'mức lửa'),
        ('強火', 'つよび', 'lửa lớn'),
        ('中火', 'ちゅうび', 'lửa vừa'),
        ('弱火', 'よわび', 'lửa nhỏ'),
        ('沸騰', 'ふっとう', 'sôi'),
        ('予熱', 'よねつ', 'làm nóng trước'),
        ('油温', 'ゆおん', 'nhiệt độ dầu'),
        ('焼き加減', 'やきかげん', 'mức độ chín khi nướng'),
        ('焦げる', 'こげる', 'bị cháy khét'),
        ('生焼け', 'なまやけ', 'chưa chín kỹ'),
        ('水切り', 'みずきり', 'để ráo nước'),
        ('湯切り', 'ゆぎり', 'chắt nước nóng'),
        ('水にさらす', 'みずにさらす', 'ngâm/xả trong nước'),
        ('千切り', 'せんぎり', 'thái sợi'),
        ('みじん切り', 'みじんぎり', 'băm nhỏ'),
        ('輪切り', 'わぎり', 'thái khoanh'),
        ('くし形切り', 'くしがたぎり', 'cắt múi cau'),
        ('さいの目切り', 'さいのめぎり', 'thái hạt lựu'),
        ('薄切り', 'うすぎり', 'thái lát mỏng'),
        ('鍋', 'なべ', 'nồi'),
        ('フライパン', 'ふらいぱん', 'chảo rán'),
        ('オーブン', 'おーぶん', 'lò nướng'),
        ('電子レンジ', 'でんしれんじ', 'lò vi sóng'),
        ('炊飯器', 'すいはんき', 'nồi cơm điện'),
        ('計量器', 'けいりょうき', 'dụng cụ cân đo'),
        ('歩留まり', 'ぶどまり', 'tỷ lệ phần nguyên liệu sử dụng được'),
        ('可食部', 'かしょくぶ', 'phần ăn được'),
        ('廃棄率', 'はいきりつ', 'tỷ lệ bỏ đi'),
    ],
    'service': [
        ('接客全般', 'せっきゃくぜんぱん', 'nghiệp vụ phục vụ khách hàng'),
        ('接客サービス', 'せっきゃくさーびす', 'dịch vụ khách hàng'),
        ('お客様', 'おきゃくさま', 'quý khách'),
        ('挨拶', 'あいさつ', 'chào hỏi'),
        ('身だしなみ', 'みだしなみ', 'diện mạo, tác phong'),
        ('表情', 'ひょうじょう', 'nét mặt'),
        ('姿勢', 'しせい', 'tư thế'),
        ('お辞儀', 'おじぎ', 'cúi chào'),
        ('案内', 'あんない', 'hướng dẫn; dẫn khách'),
        ('注文', 'ちゅうもん', 'gọi món; đơn gọi món'),
        ('注文を受ける', 'ちゅうもんをうける', 'nhận gọi món'),
        ('復唱', 'ふくしょう', 'nhắc lại để xác nhận'),
        ('配膳', 'はいぜん', 'bày và phục vụ món'),
        ('下膳', 'げぜん', 'thu dọn bát đĩa'),
        ('提供', 'ていきょう', 'cung cấp; phục vụ món'),
        ('会計', 'かいけい', 'thanh toán'),
        ('伝票', 'でんぴょう', 'phiếu gọi món; hóa đơn'),
        ('現金', 'げんきん', 'tiền mặt'),
        ('お釣り', 'おつり', 'tiền thừa'),
        ('領収書', 'りょうしゅうしょ', 'biên lai'),
        ('予約', 'よやく', 'đặt chỗ'),
        ('満席', 'まんせき', 'hết chỗ'),
        ('空席', 'くうせき', 'chỗ trống'),
        ('禁煙席', 'きんえんせき', 'chỗ không hút thuốc'),
        ('営業時間', 'えいぎょうじかん', 'giờ mở cửa'),
        ('開店', 'かいてん', 'mở cửa hàng'),
        ('閉店', 'へいてん', 'đóng cửa hàng'),
        ('営業準備', 'えいぎょうじゅんび', 'chuẩn bị mở cửa kinh doanh'),
        ('清掃作業', 'せいそうさぎょう', 'công việc vệ sinh'),
        ('苦情', 'くじょう', 'phàn nàn; khiếu nại'),
        ('責任者', 'せきにんしゃ', 'người phụ trách'),
        ('報告', 'ほうこく', 'báo cáo'),
        ('対応', 'たいおう', 'ứng phó; xử lý'),
        ('謝罪', 'しゃざい', 'xin lỗi'),
        ('食物アレルギー', 'しょくもつあれるぎー', 'dị ứng thực phẩm'),
        ('アレルゲン', 'あれるげん', 'chất gây dị ứng'),
        ('特定原材料', 'とくていげんざいりょう', 'nguyên liệu gây dị ứng bắt buộc ghi nhãn'),
        ('飲酒', 'いんしゅ', 'uống rượu'),
        ('未成年者', 'みせいねんしゃ', 'người chưa thành niên'),
        ('年齢確認', 'ねんれいかくにん', 'xác nhận độ tuổi'),
        ('栄養', 'えいよう', 'dinh dưỡng'),
        ('味覚', 'みかく', 'vị giác'),
        ('甘味', 'かんみ', 'vị ngọt'),
        ('塩味', 'えんみ', 'vị mặn'),
        ('酸味', 'さんみ', 'vị chua'),
        ('苦味', 'にがみ', 'vị đắng'),
        ('うま味', 'うまみ', 'vị umami; vị ngọt thịt'),
        ('宗教', 'しゅうきょう', 'tôn giáo'),
        ('ベジタリアン', 'べじたりあん', 'người ăn chay'),
        ('車いす', 'くるまいす', 'xe lăn'),
        ('補助犬', 'ほじょけん', 'chó hỗ trợ người khuyết tật'),
        ('高齢者', 'こうれいしゃ', 'người cao tuổi'),
        ('非常口', 'ひじょうぐち', 'lối thoát hiểm'),
        ('避難', 'ひなん', 'sơ tán'),
        ('防災', 'ぼうさい', 'phòng chống thiên tai'),
    ],
}


def expand_vocabulary(apps, schema_editor):
    VocabularyEntry = apps.get_model('study', 'VocabularyEntry')
    for category, words in VOCABULARY.items():
        for order, (word_jp, furigana, meaning_vi) in enumerate(words, start=1):
            VocabularyEntry.objects.update_or_create(
                category=category,
                word_jp=word_jp,
                defaults={
                    'furigana': furigana,
                    'meaning_vi': meaning_vi,
                    'order': order,
                    'is_published': True,
                    'source_title': '外食業技能測定試験 学習用テキスト - 日本フードサービス協会',
                    'source_url': SOURCES[category],
                },
            )
        VocabularyEntry.objects.filter(category=category).update(
            source_title='外食業技能測定試験 学習用テキスト - 日本フードサービス協会',
            source_url=SOURCES[category],
        )


def remove_expanded_vocabulary(apps, schema_editor):
    VocabularyEntry = apps.get_model('study', 'VocabularyEntry')
    for category, words in VOCABULARY.items():
        VocabularyEntry.objects.filter(
            category=category,
            word_jp__in=[word[0] for word in words],
        ).delete()


class Migration(migrations.Migration):
    dependencies = [('study', '0013_vocabularyentry_source_title_and_more')]
    operations = [migrations.RunPython(expand_vocabulary, remove_expanded_vocabulary)]
