# Generated by Django 6.1 on 2026-08-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_expand_official_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyentry',
            name='topic',
            field=models.CharField(choices=[('core', 'Kiến thức cốt lõi'), ('ingredients_tools', 'Thực phẩm, nguyên liệu và dụng cụ'), ('cooking_actions', 'Thao tác chế biến'), ('food_poisoning', 'Ngộ độc và triệu chứng'), ('temperature_numbers', 'Nhiệt độ, thời gian và tính toán'), ('communication', 'Giao tiếp với khách hàng'), ('store_operations', 'Thanh toán, đặt bàn và xử lý phàn nàn'), ('allergy_diversity', 'Dị ứng và chế độ ăn đặc biệt'), ('workplace_safety', 'An toàn, cháy nổ và sơ tán'), ('practical_planning', 'Thực hành và lập kế hoạch')], default='core', max_length=30, verbose_name='Nhóm nội dung'),
        ),
        migrations.AddIndex(
            model_name='vocabularyentry',
            index=models.Index(fields=['topic', 'is_published'], name='study_vocab_topic_f772fd_idx'),
        ),
    ]
