# Generated by Django 6.1 on 2026-08-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0017_add_vocabulary_to_300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('welcome_order', 'Đón khách và gọi món'), ('complaint', 'Phàn nàn và sai sót'), ('allergy', 'Dị ứng và yêu cầu đặc biệt'), ('payment', 'Thanh toán và đặt bàn'), ('emergency', 'Sự cố và tình huống khẩn cấp')], max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('title_jp', models.CharField(max_length=200)),
                ('title_furigana', models.CharField(blank=True, default='', max_length=250)),
                ('title_vi', models.CharField(max_length=200)),
                ('situation_jp', models.TextField(verbose_name='Bối cảnh tiếng Nhật')),
                ('situation_furigana', models.TextField(blank=True, default='')),
                ('situation_vi', models.TextField(verbose_name='Bối cảnh tiếng Việt')),
                ('customer_phrase_jp', models.TextField(blank=True, default='', verbose_name='Lời khách nói')),
                ('customer_phrase_furigana', models.TextField(blank=True, default='')),
                ('customer_phrase_vi', models.TextField(blank=True, default='')),
                ('response_jp', models.TextField(verbose_name='Câu trả lời mẫu tiếng Nhật')),
                ('response_furigana', models.TextField(blank=True, default='')),
                ('response_vi', models.TextField(verbose_name='Câu trả lời mẫu tiếng Việt')),
                ('handling_steps_vi', models.TextField(verbose_name='Các bước xử lý')),
                ('exam_note_vi', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tình huống dịch vụ',
                'verbose_name_plural': 'Tình huống ngành dịch vụ',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
