# Generated by Django 6.1 on 2026-08-16 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_plans(apps, schema_editor):
    PremiumPlan = apps.get_model('study', 'PremiumPlan')
    plans = [
        ('1 tháng', '1-thang', 30, 59000, 29000, False, 1),
        ('6 tháng', '6-thang', 180, 354000, 129000, False, 2),
        ('1 năm', '1-nam', 365, 708000, 199000, True, 3),
        ('Trọn đời', 'tron-doi', None, 999000, 299000, False, 4),
    ]
    for name, slug, days, original, sale, featured, order in plans:
        PremiumPlan.objects.create(
            name=name, slug=slug, duration_days=days,
            original_price_vnd=original, sale_price_vnd=sale,
            is_featured=featured, is_active=True, order=order,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0020_add_more_service_situations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Đang Premium')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trạng thái Premium',
                'verbose_name_plural': 'Trạng thái Premium',
            },
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Tên gói')),
                ('slug', models.SlugField(unique=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số ngày sử dụng (để trống = trọn đời)')),
                ('original_price_vnd', models.PositiveIntegerField(verbose_name='Giá gốc (VNĐ)')),
                ('sale_price_vnd', models.PositiveIntegerField(verbose_name='Giá ưu đãi (VNĐ)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ưu đãi tốt nhất')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gói Premium',
                'verbose_name_plural': 'Các gói Premium',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(create_default_plans, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PremiumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_name', models.CharField(max_length=150, verbose_name='Tên người chuyển khoản')),
                ('transfer_date', models.DateField(verbose_name='Ngày chuyển khoản')),
                ('amount_vnd', models.PositiveIntegerField(verbose_name='Số tiền (VNĐ)')),
                ('reference', models.CharField(blank=True, default='', max_length=200, verbose_name='Mã giao dịch/nội dung chuyển khoản')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='Ghi chú Admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_premium_requests', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='study.premiumplan', verbose_name='Gói Premium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu Premium',
                'verbose_name_plural': 'Yêu cầu Premium',
                'ordering': ['-created_at'],
            },
        ),
    ]
